//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SUMetadataModel", "FK_MetadataFields_MetadataModules", "MetadataModules", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SUCore.Metadata.ModuleMetadata), "MetadataFields", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SUCore.Metadata.FieldMetadata))]

// Original file name:
// Generation date: 30.11.2008 12:40:06
namespace SUCore.Metadata
{
    
    /// <summary>
    /// There are no comments for SUMetadataEntities in the schema.
    /// </summary>
    public partial class SUMetadataEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new SUMetadataEntities object using the connection string found in the 'SUMetadataEntities' section of the application configuration file.
        /// </summary>
        public SUMetadataEntities() : 
                base("name=SUMetadataEntities", "SUMetadataEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new SUMetadataEntities object.
        /// </summary>
        public SUMetadataEntities(string connectionString) : 
                base(connectionString, "SUMetadataEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new SUMetadataEntities object.
        /// </summary>
        public SUMetadataEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "SUMetadataEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for FieldMetadataSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<FieldMetadata> FieldMetadataSet
        {
            get
            {
                if ((this._FieldMetadataSet == null))
                {
                    this._FieldMetadataSet = base.CreateQuery<FieldMetadata>("[FieldMetadataSet]");
                }
                return this._FieldMetadataSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<FieldMetadata> _FieldMetadataSet;
        /// <summary>
        /// There are no comments for ModuleMetadataSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<ModuleMetadata> ModuleMetadataSet
        {
            get
            {
                if ((this._ModuleMetadataSet == null))
                {
                    this._ModuleMetadataSet = base.CreateQuery<ModuleMetadata>("[ModuleMetadataSet]");
                }
                return this._ModuleMetadataSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<ModuleMetadata> _ModuleMetadataSet;
        /// <summary>
        /// There are no comments for FieldMetadataSet in the schema.
        /// </summary>
        public void AddToFieldMetadataSet(FieldMetadata fieldMetadata)
        {
            base.AddObject("FieldMetadataSet", fieldMetadata);
        }
        /// <summary>
        /// There are no comments for ModuleMetadataSet in the schema.
        /// </summary>
        public void AddToModuleMetadataSet(ModuleMetadata moduleMetadata)
        {
            base.AddObject("ModuleMetadataSet", moduleMetadata);
        }
    }
    /// <summary>
    /// There are no comments for SUMetadataModel.FieldMetadata in the schema.
    /// </summary>
    /// <KeyProperties>
    /// FieldName
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SUMetadataModel", Name="FieldMetadata")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class FieldMetadata : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new FieldMetadata object.
        /// </summary>
        /// <param name="fieldName">Initial value of FieldName.</param>
        /// <param name="clrType">Initial value of ClrType.</param>
        public static FieldMetadata CreateFieldMetadata(string fieldName, string clrType)
        {
            FieldMetadata fieldMetadata = new FieldMetadata();
            fieldMetadata.FieldName = fieldName;
            fieldMetadata.ClrType = clrType;
            return fieldMetadata;
        }
        /// <summary>
        /// There are no comments for Property FieldName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldName
        {
            get
            {
                return this._FieldName;
            }
            set
            {
                this.OnFieldNameChanging(value);
                this.ReportPropertyChanging("FieldName");
                this._FieldName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FieldName");
                this.OnFieldNameChanged();
            }
        }
        private string _FieldName;
        partial void OnFieldNameChanging(string value);
        partial void OnFieldNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property ClrType in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ClrType
        {
            get
            {
                return this._ClrType;
            }
            set
            {
                this.OnClrTypeChanging(value);
                this.ReportPropertyChanging("ClrType");
                this._ClrType = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ClrType");
                this.OnClrTypeChanged();
            }
        }
        private string _ClrType;
        partial void OnClrTypeChanging(string value);
        partial void OnClrTypeChanged();
        /// <summary>
        /// There are no comments for MetadataModules in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SUMetadataModel", "FK_MetadataFields_MetadataModules", "MetadataModules")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public ModuleMetadata MetadataModules
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ModuleMetadata>("SUMetadataModel.FK_MetadataFields_MetadataModules", "MetadataModules").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ModuleMetadata>("SUMetadataModel.FK_MetadataFields_MetadataModules", "MetadataModules").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for MetadataModules in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<ModuleMetadata> MetadataModulesReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<ModuleMetadata>("SUMetadataModel.FK_MetadataFields_MetadataModules", "MetadataModules");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<ModuleMetadata>("SUMetadataModel.FK_MetadataFields_MetadataModules", "MetadataModules", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SUMetadataModel.ModuleMetadata in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ModuleName
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SUMetadataModel", Name="ModuleMetadata")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ModuleMetadata : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ModuleMetadata object.
        /// </summary>
        /// <param name="moduleName">Initial value of ModuleName.</param>
        public static ModuleMetadata CreateModuleMetadata(string moduleName)
        {
            ModuleMetadata moduleMetadata = new ModuleMetadata();
            moduleMetadata.ModuleName = moduleName;
            return moduleMetadata;
        }
        /// <summary>
        /// There are no comments for Property ModuleName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleName
        {
            get
            {
                return this._ModuleName;
            }
            set
            {
                this.OnModuleNameChanging(value);
                this.ReportPropertyChanging("ModuleName");
                this._ModuleName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ModuleName");
                this.OnModuleNameChanged();
            }
        }
        private string _ModuleName;
        partial void OnModuleNameChanging(string value);
        partial void OnModuleNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this.ReportPropertyChanging("Description");
                this._Description = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Description");
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for MetadataFields in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SUMetadataModel", "FK_MetadataFields_MetadataModules", "MetadataFields")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<FieldMetadata> MetadataFields
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<FieldMetadata>("SUMetadataModel.FK_MetadataFields_MetadataModules", "MetadataFields");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<FieldMetadata>("SUMetadataModel.FK_MetadataFields_MetadataModules", "MetadataFields", value);
                }
            }
        }
    }
}
